package fr.vmz.jhipster.petclinic.customer.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PetTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPetTypeAllPropertiesEquals(PetType expected, PetType actual) {
        assertPetTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertPetTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPetTypeAllUpdatablePropertiesEquals(PetType expected, PetType actual) {
        assertPetTypeUpdatableFieldsEquals(expected, actual);
        assertPetTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPetTypeAutoGeneratedPropertiesEquals(PetType expected, PetType actual) {
        assertThat(actual)
            .as("Verify PetType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPetTypeUpdatableFieldsEquals(PetType expected, PetType actual) {
        assertThat(actual)
            .as("Verify PetType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPetTypeUpdatableRelationshipsEquals(PetType expected, PetType actual) {
        // empty method
    }
}
