package fr.vmz.jhipster.petclinic.vet.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVetAllPropertiesEquals(Vet expected, Vet actual) {
        assertVetAutoGeneratedPropertiesEquals(expected, actual);
        assertVetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVetAllUpdatablePropertiesEquals(Vet expected, Vet actual) {
        assertVetUpdatableFieldsEquals(expected, actual);
        assertVetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVetAutoGeneratedPropertiesEquals(Vet expected, Vet actual) {
        assertThat(actual)
            .as("Verify Vet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVetUpdatableFieldsEquals(Vet expected, Vet actual) {
        assertThat(actual)
            .as("Verify Vet relevant properties")
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVetUpdatableRelationshipsEquals(Vet expected, Vet actual) {
        assertThat(actual)
            .as("Verify Vet relationships")
            .satisfies(a -> assertThat(a.getSpecialties()).as("check specialties").isEqualTo(expected.getSpecialties()));
    }
}
